---
#
# Ansible managed
#
repository:
  description: Install and configure collectd on your system.
  homepage: https://robertdebock.nl/
  topics: collectd, security, ansible, molecule, tox, playbook
